---
title: "Warrenkb_FinalHomeworkCode_05"
author: "Warrenkevin Henderson"
date: "11/17/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lmodel2)
KC <- read.csv("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/KamilarAndCooperData.csv")
head(KC)
summary(KC)
````
```{r}
Home_Range <- log(KC$HomeRange_km2)
Body_Mass_Female_Mean <- log(KC$Body_mass_female_mean)
```
```{r}
cbind <- cbind(KC, Home_Range, Body_Mass_Female_Mean)
l <- lmodel2(Home_Range~Body_Mass_Female_Mean, data= cbind  , range.y ="Interval" , range.x="Relative"  , nperm=0)
mx <- l$regression.results$slope
b <-l$regression.results$Intercept
```

```{r}
S_1 <- NULL
S_2 <- NULL
for (i in 1:1000) { S_1[[i]] <- sample(KC$HomeRange_km2,size =100, replace=TRUE) 
S_2[[i]] <- sample(KC$Body_mass_female_mean, size = 100, replace=TRUE)}

```
```{r}
mm <- NULL
for (i in 1:1000) {
  mm[[i]] <- lmodel2(S_1[[i]]~S_2[[i]],data = KC, range.y = "Interval", range.x = "relative")
b[i] <-mm[[i]]$regression.results$Slope[1]
mx[i] <-mm[[i]]$regression.results$Intercept[1]
}
```

```{r}
sd0 <- sd(b)
sd0

sd1 <- sd(mx)
sd1
A <- lm(Home_Range~Body_Mass_Female_Mean)
B <- coef(summary(A))
CI <- confint(A, level = 0.95)
df <- data.frame(Bootstrapping_SE = c(sd0, sd1), Bootstrapping_95 = c(quantile(b, 0.95),quantile(mx, 0.95)))
table <- cbind(B[,1:2],df,CI)
table


```
#### Questions 1: Not quite sure i understand this question
#### Question 2: It aligns with the intercept


